# Generated by Django 4.1.3 on 2022-12-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
                ('picture', models.ImageField(upload_to='')),
                ('licence', models.FileField(upload_to='')),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
