# Generated by Django 4.1.3 on 2022-12-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='licence',
        ),
        migrations.AddField(
            model_name='user',
            name='license',
            field=models.FileField(default=None, upload_to='media/<django.db.models.fields.AutoField>/license/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(height_field=350, upload_to='media/<django.db.models.fields.AutoField>/picture', width_field=350),
        ),
    ]
