# Generated by Django 4.1.3 on 2022-12-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_user_licence_user_license_alter_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='license',
        ),
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
    ]
